# Site settings
title: The unsaid
description:    
url:            

# Google Analytics
google_analytics: 

# Author
author:
  name:         Belligerent Buffoon
  url:          https://incarcerated-thoughts.github.io
  email:        belligerentbuffoon@outlook.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock ]

# Disqus (Set to your disqus id)
disqus:         belligerentbuffoon
